"""maybe it's better

Revision ID: 561f356e737d
Revises: 74b6f3ef19cd
Create Date: 2018-07-06 00:51:01.455602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561f356e737d'
down_revision = '74b6f3ef19cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_to_Role',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User_to_Role')
    # ### end Alembic commands ###
